language: ruby
sudo: false
rvm:
  - 2.3.1
  - 2.2.5
  - jruby-9.0.5.0
  - rbx-2
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2
addons:
  postgresql: "9.3"
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
