language: ruby
sudo: false
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - jruby-9.0.5.0
gemfile:
  - gemfiles/ar51.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
