language: ruby
sudo: false
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-1.7
  - jruby-9.0.4.0
  - rbx-2
gemfile:
  - gemfiles/ar42.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
addons:
  postgresql: "9.3"
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
