language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
env:
  - POSTGIS=2.0
gemfile:
  - gemfiles/ar42.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
